import { createStore } from "vuex";
import { config } from "vuex-module-decorators";
import createPersistedState from "vuex-persistedstate";

import AccountModule from "@/store/modules/accounts/accounts";
import AuthModule from "@/store/modules/miscellaneous/AuthModule";
import BodyModule from "@/store/modules/miscellaneous/BodyModule";
import BreadcrumbsModule from "@/store/modules/miscellaneous/BreadcrumbsModule";
import ConfigModule from "@/store/modules/miscellaneous/ConfigModule";
import CustomerModule from "@/store/modules/customer/customer";
import CrushingStoneModule from "@/store/modules/crushingStone/crushingStone";
import DriverModule from "@/store/modules/drivers/driver";
import IncomeExpenses from "@/store/modules/incomeExpenses/incomeExpenses";
import ItemModule from "@/store/modules/items/item";
import LcModule from "@/store/modules/lc/lc";
import LookupDataModule from "@/store/modules/lookupData/lookupData";
import PurchaseOrder from "@/store/modules/purchase/purchaseOrder";
import PurchaseInvoice from "@/store/modules/purchase/purchaseInvoice";
import PoTruckLoadingModule from "@/store/modules/purchase/poTruckLoading";
import SalesOrderModule from "@/store/modules/sales_order/sales_order";
import SoDeliveryModule from "@/store/modules/so_delivery/so_delivery";
// <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< main
import SoInvoiceModule from "@/store/modules/so_invoice/so_invoice";
import SoPaymentModule from "@/store/modules/so_payments/so_payments";
// ====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
import SupplierModule from "@/store/modules/supplier/supplier";
import VehicleModule from "@/store/modules/vehicles/vehicle";
// >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> SIM-43-Create-UI-for-PO-Receive
import GeneratorLogModule from "@/store/modules/generators/generators";
import OtherReportsModule from "@/store/modules/otherReports/other_reports";
import DashboardModule from "@/store/modules/dashboard/dashboard";

config.rawError = true;

const store = createStore({
  modules: {
    AuthModule,
    BodyModule,
    BreadcrumbsModule,
    ConfigModule,
    AccountModule,
    CustomerModule,
    CrushingStoneModule,
    LookupDataModule,
    ItemModule,
    IncomeExpenses,
    DriverModule,
    VehicleModule,
    LcModule,
    PurchaseOrder,
    PurchaseInvoice,
    SalesOrderModule,
    PoTruckLoadingModule,
    SoDeliveryModule,
    // <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< main
    SoInvoiceModule,
    SoPaymentModule,
    // ====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
    SupplierModule,
    // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> SIM-43-Create-UI-for-PO-Receive
    GeneratorLogModule,
    OtherReportsModule,
    DashboardModule,
  },
  plugins: [createPersistedState()],
});

export default store;
